- assets/hb/modules/blog/scss/_terms.scss
- layouts/_default/term.html
- layouts/partials/hb/modules/blog/post/meta/authors.html
- layouts/partials/hb/modules/blog/term/matrixes.html
- layouts/partials/hb/modules/blog/term/profile.html
- layouts/partials/hb/modules/blog/term/socials.html
Show the description
Show the social links
Show the matrixes
> feat: change term layout

- layouts/partials/hb/modules/blog/post/comments.html
- modules/giscus/layouts/partials/hugopress/modules/hb-blog-comments-giscus/hooks/body-end.html
> feat: add the comments parameter and anchor

- layouts/_default/index.html
- layouts/partials/hb/modules/blog/index.html
Remove the home.recent_posts parameter
> feat!: paginate the homepage

- hugo.toml
- layouts/partials/hb/modules/blog/post/card-img.html
- layouts/partials/hb/modules/blog/post/card.html
> feat: add the post_thumbnail parameter

- assets/hb/modules/blog/scss/post/_card.scss
- hugo.toml
- layouts/partials/hb/modules/blog/post/card-img.html
Add the post_thumbnail_placeholder parameter, use site title if not set
> feat: add the thumbnail placeholder

- assets/hb/modules/blog/scss/_sidebar.scss
- assets/hb/modules/blog/scss/index.scss
- assets/hb/modules/blog/scss/post/_main.scss
- assets/hb/modules/blog/scss/variables.tmpl.scss
- layouts/_default/term.html
- layouts/partials/hb/modules/blog/functions/has-sidebar.html
- layouts/partials/hb/modules/blog/index.html
- layouts/partials/hb/modules/blog/list.html
- layouts/partials/hb/modules/blog/post/card.html
- layouts/partials/hb/modules/blog/posts.html
- layouts/partials/hb/modules/blog/sidebar.html
- layouts/partials/hb/modules/blog/single.html
- layouts/partials/hb/modules/blog/taxonomies/toggle.html
> feat: add the optional sidebar implementation

- hugo.toml
- layouts/partials/hugopress/modules/hb-blog/attributes/hb-main.html
> feat: add the full_width parameter to take full width

- assets/hb/modules/blog/scss/_sidebar.scss
> fix: sticky ToC not working when enabling sidebar modules

- layouts/_default/term.html
- layouts/partials/hb/modules/blog/archives/list.html
- layouts/partials/hb/modules/blog/list.html
- layouts/partials/hb/modules/blog/post/comments.html
- layouts/partials/hb/modules/blog/single.html
> fix: revert "perf: caching partials"

- modules/sidebar/posts/hugo.toml
- modules/sidebar/posts/layouts/partials/hugopress/modules/hb-blog-sidebar-posts/hooks/hb-blog-sidebar.html
feat(sidebar-posts): add the fill parameter, when true (default), the tabs take full width
> feat(sidebar-posts): add the style parameter, available options: pills (default), tabs and underline

- i18n/ko.toml
'Read More' would be '자세한 내용 보기' in Korean. There might be shorter words for it, but I can't think of it for now.
> Update Korean translation

- layouts/_default/term.html
> style: show more posts per row on term list pages when there is no sidebar

- i18n/fr.toml
Hi,
Here is a proposal of i18n file dedicated to the French language.
Let me know, thank you
> feat(i18n): add FR translation file

- modules/sidebar/posts/i18n/pt-br.toml
> feat(i18n): add PT-BR translation file

- modules/sidebar/posts/i18n/es.toml
Updated "modules/sidebar/posts/i18n/es.toml" with Spanish translations.
> Update "modules/sidebar/posts/i18n/es.toml" with Spanish translations.

- i18n/pt-br.toml
> feat(i18n): update PT-BR translation file

- assets/hb/modules/blog/scss/_sidebar.scss
- assets/hb/modules/blog/scss/variables.tmpl.scss
- hugo.toml
```yaml
hb:
blog:
sidebar:
sticky: false
```
> feat: add the sidebar.sticky parameter, to disable sticky behaviour by setting it to `false`

- modules/decap-cms/assets/decap-cms/preview-templates/hb/blog-post.ts
> fix(decap-cms): remove data widgets placeholder from preview template

- assets/hb/modules/blog/scss/_sidebar.scss
- assets/hb/modules/blog/scss/post/_toc.scss
style: change sidebar and ToC scrollbar width as thin
> style: highlight sidebar and ToC scrollbar on hover

- modules/post-nav/layouts/partials/hb/modules/blog-post-nav/index.html
> style(post-nav): minor tweak

- i18n/de.toml
- modules/sidebar/taxonomies/CHANGELOG.md
This PR fixes the German translation and fixes a typo on the way.
> Fix German translation

- layouts/_default/terms.html
- layouts/authors/terms.html
- layouts/partials/hb/modules/blog/archives/list.html
- layouts/partials/hb/modules/blog/archives/posts.html
- layouts/partials/hb/modules/blog/author/image.html
- layouts/partials/hb/modules/blog/index.html
- layouts/partials/hb/modules/blog/post/card.html
- layouts/partials/hb/modules/blog/post/meta/first-section.html
- layouts/partials/hb/modules/blog/post/toc.html
- layouts/partials/hb/modules/blog/single.html
- layouts/partials/hb/modules/blog/taxonomies/default.html
- layouts/partials/hb/modules/blog/taxonomies/toggle.html
- layouts/partials/hb/modules/blog/term/socials.html
- layouts/partials/hugopress/modules/hb-blog/hooks/head-begin.html
- modules/decap-cms/assets/decap-cms/preview-templates/hb/blog-post.ts
- modules/post-nav/layouts/partials/hb/modules/blog-post-nav/index.html
- modules/related-posts/layouts/partials/hb/modules/blog-related-posts/vertical.html
- modules/sidebar/posts/layouts/partials/hb/modules/blog-sidebar-posts/vertical.html
- modules/sidebar/posts/layouts/partials/hugopress/modules/hb-blog-sidebar-posts/hooks/hb-blog-sidebar.html
- modules/sidebar/profile/layouts/partials/hugopress/modules/hb-blog-sidebar-profile/hooks/hb-blog-sidebar.html
- modules/sticky-till-the-end/assets/hb/modules/blog-sticky-till-the-end/js/index.ts
> chore: format codes

- layouts/partials/hb/modules/blog/post/card.html
- layouts/partials/hb/modules/blog/single.html
> feat: add the hb-blog-post-meta hook

- layouts/_default/rss.xml
> fix(rss): correct copyright `{year}` placeholder parsing

- layouts/partials/hb/modules/blog/sidebar.html
Hide the sidebar if `false`
Closes #992
> feat: add the `sidebar` page parameter
